services:
  go-service:
    image: go-service:day3
    container_name: go-service
    ports:
      - "8080:8080"
    volumes:
      - ./shared-logs:/shared-logs
    environment:
      - LOG_FILE=/shared-logs/go-service.log
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./observability/prometheus/rules:/etc/prometheus/rules:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    depends_on:
      - go-service
      - alertmanager

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./observability/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    command: 
      - "--config.file=/etc/alertmanager/alertmanager.yml"
  
  alert-receiver:
    build:
      context: ./alert-receiver
    container_name: alert-receiver
    ports:
      - "5001:5001"
    volumes:
      - ./incidents:/incidents
      - ./shared-logs:/shared-logs
    environment:
      - INCIDENT_DIR=/incidents
      - /var/run/docker.sock:/var/run/docker.sock
      - LOKI_URL=http://loki:3100
      - FLASK_APP=app.py
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001"]

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki/loki-config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    volumes:
      - ./observability/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  loki-data:

