global: {}

route:
  receiver: "webhook-receiver"
  group_by: ["alertname", "job"]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: "webhook-receiver"
    webhook_configs:
      - url: "http://alert-receiver:5001/alert"
        send_resolved: true